/* Config Tailwind Play CDN · Material 3 verde institucional EHU.
   Se carga DESPUÉS del CDN (ver index.html). */
tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#006d3d',
        'on-primary': '#ffffff',
        'primary-container': '#5fd790',
        'on-primary-container': '#005b32',
        'primary-fixed': '#82fab0',
        'primary-fixed-dim': '#65dd95',
        secondary: '#226b3e',
        'on-secondary': '#ffffff',
        'secondary-container': '#a6f1b7',
        'on-secondary-container': '#287042',
        'secondary-fixed': '#a9f3ba',
        'secondary-fixed-dim': '#8dd7a0',
        tertiary: '#625e54',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c6c0b4',
        'on-tertiary-container': '#524e44',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f6',
        'on-background': '#1b1c1a',
        surface: '#fbf9f6',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#3e4a40',
        'surface-bright': '#fbf9f6',
        'surface-dim': '#dbdad7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#f0eeea',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'surface-variant': '#e4e2df',
        outline: '#6d7a6f',
        'outline-variant': '#bdcabd',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        'inverse-primary': '#65dd95',
      },
      fontFamily: {
        serif: ['Source Serif 4', 'ui-serif', 'Georgia', 'serif'],
        sans: ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
};
